# Generated by Django 5.2.3 on 2025-06-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=5000)),
                ('curr_price', models.FloatField()),
            ],
        ),
    ]
