# Generated by Django 5.2.3 on 2025-07-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_rename_userstocks_userstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pancard_image',
            field=models.ImageField(upload_to='uploads/pancards/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_image',
            field=models.ImageField(upload_to='uploads/users/'),
        ),
    ]
