# Generated by Django 5.2.3 on 2025-07-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_userinfo_pancard_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pancard_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/pancards/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pancard_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/users/'),
        ),
    ]
